// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrOxR0X5vkySp8Itvhc2owkA4XjwSDo04',
    appId: '1:160006448180:web:ef48ffa8cb88ee08e29661',
    messagingSenderId: '160006448180',
    projectId: 'fir-flutter-codelab-351d0',
    authDomain: 'fir-flutter-codelab-351d0.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelab-351d0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-351d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSiXwxlbC9LVQ7kGtdU0xr1AbMrRrU8w',
    appId: '1:160006448180:android:3dd6c8ad06de8e84e29661',
    messagingSenderId: '160006448180',
    projectId: 'fir-flutter-codelab-351d0',
    databaseURL: 'https://fir-flutter-codelab-351d0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-351d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjHqnKQn4Oi_eu53OUFagqzHUF5L4RV0',
    appId: '1:160006448180:ios:129120a3ee840875e29661',
    messagingSenderId: '160006448180',
    projectId: 'fir-flutter-codelab-351d0',
    databaseURL: 'https://fir-flutter-codelab-351d0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-351d0.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCjHqnKQn4Oi_eu53OUFagqzHUF5L4RV0',
    appId: '1:160006448180:ios:129120a3ee840875e29661',
    messagingSenderId: '160006448180',
    projectId: 'fir-flutter-codelab-351d0',
    databaseURL: 'https://fir-flutter-codelab-351d0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-351d0.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrOxR0X5vkySp8Itvhc2owkA4XjwSDo04',
    appId: '1:160006448180:web:cd0997d0336a6f3ee29661',
    messagingSenderId: '160006448180',
    projectId: 'fir-flutter-codelab-351d0',
    authDomain: 'fir-flutter-codelab-351d0.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelab-351d0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-351d0.appspot.com',
  );
}